### ISSUE TITLE
Any chance you could change the name of this to "nanocurrency"?

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [Matoking/nanolib#3]
_pynanocurrency_ is just confusing, because you see it installed as _pynanocurrency_, but you must import _nanocurrency_ to use it

or _nanolib_, something shorter to make using it faster

**Comment by Matoking** [comment]
I originally named it `pynanocurrency` instead of `nanocurrency` because:
* It makes it clear it's a Python library. Popular packages on PyPi have the `py` prefix, such as `PyYAML` which is imported using `import yaml` in actual Python code.
* To prevent confusion with [the GitHub organization](https://github.com/nanocurrency/) name used by the NANO team.

The confusion between the package name and the module name is understandable and I think the current name is a bit on the long side.

`nanolib` would actually fit the bill between being short and snazzy, following a convention (eg. `urllib`, `contextlib`, `matplotlib`, ...) and having a name that doesn't conflict with any existing packages. And the package is still on 0.x, so changing the name is still OK.

**Comment by Laurentiu-Andronache** [comment]
Please nanolib then. It's not taken on pypi: https://pypi.org/search/?q=nanolib

**Comment by Matoking** [comment]
I've renamed the project to **nanolib**. The same name is used for both the package name on PyPI and the actual module developers import in Python code.

**Comment by Laurentiu-Andronache** [comment]
This is glorious. What's your ID on Discord btw, in the Nano group?

**Comment by Matoking** [comment]
> This is glorious. What's your ID on Discord btw, in the Nano group?

It's Matoking#1943. I lurk there for the most part, though.
