### ISSUE TITLE
Ability to solve work through a work peer

### ISSUE THREAD

**Issue by guilhermelawless** [Matoking/nanolib#5]
Would it be possible to add the ability to solve work via a request `{"action": "work_generate", "hash": "HASH", "difficulty": "123"}' to a user given [IP]:port ?

RPC documentation: https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#work-generate

This would add the ability to use nanolib with external servers like https://github.com/nanocurrency/nano-work-server

**Comment by Matoking** [comment]
I intend to keep nanolib focused on the NANO protocol, not any implementations and their own APIs, at least for the time being. There are a few reasons for this:
* The RPC protocol in the NANO node changes more often than the protocol and would require more effort to maintain.
* Python libraries for the RPC API already exist (eg. [nanopy](https://github.com/nano128/nanopy))
* API design questions (eg. async support, implementation using requests or urllib, possibility to cancel work generation, etc.). Since implementing the `work_generate` API call is simple enough, it would be better to let the developer decide instead of pushing our own opinionated solution.

**Comment by guilhermelawless** [comment]
That's fair enough, thank you.
